// monEZ - Country & Localization Data

export const countries = {
  "IN": { name: "India", flag: "🇮🇳", phoneCode: "+91" },
  "US": { name: "United States", flag: "🇺🇸", phoneCode: "+1" },
  "GB": { name: "United Kingdom", flag: "🇬🇧", phoneCode: "+44" },
  "AE": { name: "UAE", flag: "🇦🇪", phoneCode: "+971" },
  "SA": { name: "Saudi Arabia", flag: "🇸🇦", phoneCode: "+966" },
  "SG": { name: "Singapore", flag: "🇸🇬", phoneCode: "+65" },
  "CA": { name: "Canada", flag: "🇨🇦", phoneCode: "+1" },
  "AU": { name: "Australia", flag: "🇦🇺", phoneCode: "+61" },
  "PH": { name: "Philippines", flag: "🇵🇭", phoneCode: "+63" },
  "ID": { name: "Indonesia", flag: "🇮🇩", phoneCode: "+62" },
  "MY": { name: "Malaysia", flag: "🇲🇾", phoneCode: "+60" },
  "TH": { name: "Thailand", flag: "🇹🇭", phoneCode: "+66" },
  "VN": { name: "Vietnam", flag: "🇻🇳", phoneCode: "+84" },
  "KR": { name: "South Korea", flag: "🇰🇷", phoneCode: "+82" },
  "JP": { name: "Japan", flag: "🇯🇵", phoneCode: "+81" },
  "CN": { name: "China", flag: "🇨🇳", phoneCode: "+86" },
  "BR": { name: "Brazil", flag: "🇧🇷", phoneCode: "+55" },
  "MX": { name: "Mexico", flag: "🇲🇽", phoneCode: "+52" },
  "AR": { name: "Argentina", flag: "🇦🇷", phoneCode: "+54" },
  "RU": { name: "Russia", flag: "🇷🇺", phoneCode: "+7" },
  "TR": { name: "Turkey", flag: "🇹🇷", phoneCode: "+90" },
  "ZA": { name: "South Africa", flag: "🇿🇦", phoneCode: "+27" },
  "NG": { name: "Nigeria", flag: "🇳🇬", phoneCode: "+234" },
  "KE": { name: "Kenya", flag: "🇰🇪", phoneCode: "+254" },
  "EG": { name: "Egypt", flag: "🇪🇬", phoneCode: "+20" },
  "PK": { name: "Pakistan", flag: "🇵🇰", phoneCode: "+92" },
  "BD": { name: "Bangladesh", flag: "🇧🇩", phoneCode: "+880" },
  "LK": { name: "Sri Lanka", flag: "🇱🇰", phoneCode: "+94" },
  "NP": { name: "Nepal", flag: "🇳🇵", phoneCode: "+977" },
  "FR": { name: "France", flag: "🇫🇷", phoneCode: "+33" },
  "DE": { name: "Germany", flag: "🇩🇪", phoneCode: "+49" },
  "ES": { name: "Spain", flag: "🇪🇸", phoneCode: "+34" },
  "IT": { name: "Italy", flag: "🇮🇹", phoneCode: "+39" },
  "PL": { name: "Poland", flag: "🇵🇱", phoneCode: "+48" },
  "NL": { name: "Netherlands", flag: "🇳🇱", phoneCode: "+31" },
  "SE": { name: "Sweden", flag: "🇸🇪", phoneCode: "+46" },
  "NO": { name: "Norway", flag: "🇳🇴", phoneCode: "+47" },
  "DK": { name: "Denmark", flag: "🇩🇰", phoneCode: "+45" },
  "FI": { name: "Finland", flag: "🇫🇮", phoneCode: "+358" },
  "CH": { name: "Switzerland", flag: "🇨🇭", phoneCode: "+41" },
  "AT": { name: "Austria", flag: "🇦🇹", phoneCode: "+43" },
  "BE": { name: "Belgium", flag: "🇧🇪", phoneCode: "+32" },
  "PT": { name: "Portugal", flag: "🇵🇹", phoneCode: "+351" },
  "GR": { name: "Greece", flag: "🇬🇷", phoneCode: "+30" },
  "CZ": { name: "Czech Republic", flag: "🇨🇿", phoneCode: "+420" },
  "HU": { name: "Hungary", flag: "🇭🇺", phoneCode: "+36" },
  "RO": { name: "Romania", flag: "🇷🇴", phoneCode: "+40" },
  "IL": { name: "Israel", flag: "🇮🇱", phoneCode: "+972" },
  "NZ": { name: "New Zealand", flag: "🇳🇿", phoneCode: "+64" }
};

export const countryDefaults = {
  "IN": {
    languages: ["hi", "en", "bn", "te", "mr", "ta", "gu", "kn", "ml", "pa"],
    primaryLanguage: "hi",
    currency: "INR",
    timezone: "Asia/Kolkata",
    paymentMethods: ["upi", "paytm", "phonepe", "googlepay"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "en-IN"
  },
  "US": {
    languages: ["en", "es"],
    primaryLanguage: "en",
    currency: "USD",
    timezone: "America/New_York",
    paymentMethods: ["venmo", "paypal", "zelle", "cashapp"],
    dateFormat: "MM/DD/YYYY",
    numberFormat: "en-US"
  },
  "GB": {
    languages: ["en"],
    primaryLanguage: "en",
    currency: "GBP",
    timezone: "Europe/London",
    paymentMethods: ["paypal", "bank_transfer", "revolut"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "en-GB"
  },
  "AE": {
    languages: ["ar", "en"],
    primaryLanguage: "ar",
    currency: "AED",
    timezone: "Asia/Dubai",
    paymentMethods: ["bank_transfer", "paypal"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "ar-AE"
  },
  "SA": {
    languages: ["ar", "en"],
    primaryLanguage: "ar",
    currency: "SAR",
    timezone: "Asia/Riyadh",
    paymentMethods: ["bank_transfer", "stc_pay"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "ar-SA"
  },
  "SG": {
    languages: ["en", "zh-CN", "ms", "ta"],
    primaryLanguage: "en",
    currency: "SGD",
    timezone: "Asia/Singapore",
    paymentMethods: ["paynow", "grabpay", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "en-SG"
  },
  "CA": {
    languages: ["en", "fr"],
    primaryLanguage: "en",
    currency: "CAD",
    timezone: "America/Toronto",
    paymentMethods: ["interac", "paypal", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "en-CA"
  },
  "AU": {
    languages: ["en"],
    primaryLanguage: "en",
    currency: "AUD",
    timezone: "Australia/Sydney",
    paymentMethods: ["paypal", "bank_transfer", "payid"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "en-AU"
  },
  "PH": {
    languages: ["fil", "en"],
    primaryLanguage: "fil",
    currency: "PHP",
    timezone: "Asia/Manila",
    paymentMethods: ["gcash", "paymaya", "bank_transfer"],
    dateFormat: "MM/DD/YYYY",
    numberFormat: "en-PH"
  },
  "ID": {
    languages: ["id", "jv", "su"],
    primaryLanguage: "id",
    currency: "IDR",
    timezone: "Asia/Jakarta",
    paymentMethods: ["gopay", "ovo", "dana", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "id-ID"
  },
  "MY": {
    languages: ["ms", "en", "zh-CN", "ta"],
    primaryLanguage: "ms",
    currency: "MYR",
    timezone: "Asia/Kuala_Lumpur",
    paymentMethods: ["tng_wallet", "grabpay", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "ms-MY"
  },
  "TH": {
    languages: ["th", "en"],
    primaryLanguage: "th",
    currency: "THB",
    timezone: "Asia/Bangkok",
    paymentMethods: ["promptpay", "truemoney", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "th-TH"
  },
  "VN": {
    languages: ["vi", "en"],
    primaryLanguage: "vi",
    currency: "VND",
    timezone: "Asia/Ho_Chi_Minh",
    paymentMethods: ["momo", "zalopay", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "vi-VN"
  },
  "KR": {
    languages: ["ko", "en"],
    primaryLanguage: "ko",
    currency: "KRW",
    timezone: "Asia/Seoul",
    paymentMethods: ["kakaopay", "naverpay", "bank_transfer"],
    dateFormat: "YYYY-MM-DD",
    numberFormat: "ko-KR"
  },
  "JP": {
    languages: ["ja", "en"],
    primaryLanguage: "ja",
    currency: "JPY",
    timezone: "Asia/Tokyo",
    paymentMethods: ["line_pay", "paypay", "bank_transfer"],
    dateFormat: "YYYY/MM/DD",
    numberFormat: "ja-JP"
  },
  "CN": {
    languages: ["zh-CN", "en"],
    primaryLanguage: "zh-CN",
    currency: "CNY",
    timezone: "Asia/Shanghai",
    paymentMethods: ["wechat_pay", "alipay"],
    dateFormat: "YYYY-MM-DD",
    numberFormat: "zh-CN"
  },
  "BR": {
    languages: ["pt", "es"],
    primaryLanguage: "pt",
    currency: "BRL",
    timezone: "America/Sao_Paulo",
    paymentMethods: ["pix", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "pt-BR"
  },
  "MX": {
    languages: ["es", "en"],
    primaryLanguage: "es",
    currency: "MXN",
    timezone: "America/Mexico_City",
    paymentMethods: ["oxxo", "spei", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "es-MX"
  },
  "AR": {
    languages: ["es", "en"],
    primaryLanguage: "es",
    currency: "ARS",
    timezone: "America/Argentina/Buenos_Aires",
    paymentMethods: ["mercado_pago", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "es-AR"
  },
  "RU": {
    languages: ["ru", "en"],
    primaryLanguage: "ru",
    currency: "RUB",
    timezone: "Europe/Moscow",
    paymentMethods: ["yandex_money", "qiwi", "bank_transfer"],
    dateFormat: "DD.MM.YYYY",
    numberFormat: "ru-RU"
  },
  "TR": {
    languages: ["tr", "en"],
    primaryLanguage: "tr",
    currency: "TRY",
    timezone: "Europe/Istanbul",
    paymentMethods: ["papara", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "tr-TR"
  },
  "ZA": {
    languages: ["en", "af", "zu", "xh"],
    primaryLanguage: "en",
    currency: "ZAR",
    timezone: "Africa/Johannesburg",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "YYYY/MM/DD",
    numberFormat: "en-ZA"
  },
  "NG": {
    languages: ["en", "yo", "ig", "ha"],
    primaryLanguage: "en",
    currency: "NGN",
    timezone: "Africa/Lagos",
    paymentMethods: ["paystack", "flutterwave", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "en-NG"
  },
  "KE": {
    languages: ["sw", "en"],
    primaryLanguage: "sw",
    currency: "KES",
    timezone: "Africa/Nairobi",
    paymentMethods: ["mpesa", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "sw-KE"
  },
  "EG": {
    languages: ["ar", "en"],
    primaryLanguage: "ar",
    currency: "EGP",
    timezone: "Africa/Cairo",
    paymentMethods: ["fawry", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "ar-EG"
  },
  "PK": {
    languages: ["ur", "en", "pa", "sd"],
    primaryLanguage: "ur",
    currency: "PKR",
    timezone: "Asia/Karachi",
    paymentMethods: ["easypaisa", "jazzcash", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "ur-PK"
  },
  "BD": {
    languages: ["bn", "en"],
    primaryLanguage: "bn",
    currency: "BDT",
    timezone: "Asia/Dhaka",
    paymentMethods: ["bkash", "nagad", "rocket"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "bn-BD"
  },
  "LK": {
    languages: ["si", "ta", "en"],
    primaryLanguage: "si",
    currency: "LKR",
    timezone: "Asia/Colombo",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "si-LK"
  },
  "NP": {
    languages: ["ne", "en"],
    primaryLanguage: "ne",
    currency: "NPR",
    timezone: "Asia/Kathmandu",
    paymentMethods: ["esewa", "khalti", "bank_transfer"],
    dateFormat: "YYYY/MM/DD",
    numberFormat: "ne-NP"
  },
  "FR": {
    languages: ["fr", "en"],
    primaryLanguage: "fr",
    currency: "EUR",
    timezone: "Europe/Paris",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "fr-FR"
  },
  "DE": {
    languages: ["de", "en"],
    primaryLanguage: "de",
    currency: "EUR",
    timezone: "Europe/Berlin",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD.MM.YYYY",
    numberFormat: "de-DE"
  },
  "ES": {
    languages: ["es", "ca", "eu", "gl"],
    primaryLanguage: "es",
    currency: "EUR",
    timezone: "Europe/Madrid",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "es-ES"
  },
  "IT": {
    languages: ["it", "en"],
    primaryLanguage: "it",
    currency: "EUR",
    timezone: "Europe/Rome",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "it-IT"
  },
  "PL": {
    languages: ["pl", "en"],
    primaryLanguage: "pl",
    currency: "PLN",
    timezone: "Europe/Warsaw",
    paymentMethods: ["blik", "bank_transfer"],
    dateFormat: "DD.MM.YYYY",
    numberFormat: "pl-PL"
  },
  "NL": {
    languages: ["nl", "en"],
    primaryLanguage: "nl",
    currency: "EUR",
    timezone: "Europe/Amsterdam",
    paymentMethods: ["ideal", "paypal", "bank_transfer"],
    dateFormat: "DD-MM-YYYY",
    numberFormat: "nl-NL"
  },
  "SE": {
    languages: ["sv", "en"],
    primaryLanguage: "sv",
    currency: "SEK",
    timezone: "Europe/Stockholm",
    paymentMethods: ["swish", "bank_transfer"],
    dateFormat: "YYYY-MM-DD",
    numberFormat: "sv-SE"
  },
  "NO": {
    languages: ["no", "en"],
    primaryLanguage: "no",
    currency: "NOK",
    timezone: "Europe/Oslo",
    paymentMethods: ["vipps", "bank_transfer"],
    dateFormat: "DD.MM.YYYY",
    numberFormat: "nb-NO"
  },
  "DK": {
    languages: ["da", "en"],
    primaryLanguage: "da",
    currency: "DKK",
    timezone: "Europe/Copenhagen",
    paymentMethods: ["mobilepay", "bank_transfer"],
    dateFormat: "DD-MM-YYYY",
    numberFormat: "da-DK"
  },
  "FI": {
    languages: ["fi", "sv", "en"],
    primaryLanguage: "fi",
    currency: "EUR",
    timezone: "Europe/Helsinki",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD.MM.YYYY",
    numberFormat: "fi-FI"
  },
  "CH": {
    languages: ["de", "fr", "it", "en"],
    primaryLanguage: "de",
    currency: "CHF",
    timezone: "Europe/Zurich",
    paymentMethods: ["twint", "paypal", "bank_transfer"],
    dateFormat: "DD.MM.YYYY",
    numberFormat: "de-CH"
  },
  "AT": {
    languages: ["de", "en"],
    primaryLanguage: "de",
    currency: "EUR",
    timezone: "Europe/Vienna",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD.MM.YYYY",
    numberFormat: "de-AT"
  },
  "BE": {
    languages: ["nl", "fr", "de", "en"],
    primaryLanguage: "nl",
    currency: "EUR",
    timezone: "Europe/Brussels",
    paymentMethods: ["bancontact", "paypal", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "nl-BE"
  },
  "PT": {
    languages: ["pt", "en"],
    primaryLanguage: "pt",
    currency: "EUR",
    timezone: "Europe/Lisbon",
    paymentMethods: ["multibanco", "paypal", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "pt-PT"
  },
  "GR": {
    languages: ["el", "en"],
    primaryLanguage: "el",
    currency: "EUR",
    timezone: "Europe/Athens",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "el-GR"
  },
  "CZ": {
    languages: ["cs", "en"],
    primaryLanguage: "cs",
    currency: "CZK",
    timezone: "Europe/Prague",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD.MM.YYYY",
    numberFormat: "cs-CZ"
  },
  "HU": {
    languages: ["hu", "en"],
    primaryLanguage: "hu",
    currency: "HUF",
    timezone: "Europe/Budapest",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "YYYY.MM.DD",
    numberFormat: "hu-HU"
  },
  "RO": {
    languages: ["ro", "en"],
    primaryLanguage: "ro",
    currency: "RON",
    timezone: "Europe/Bucharest",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD.MM.YYYY",
    numberFormat: "ro-RO"
  },
  "IL": {
    languages: ["he", "ar", "en"],
    primaryLanguage: "he",
    currency: "ILS",
    timezone: "Asia/Jerusalem",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "he-IL"
  },
  "NZ": {
    languages: ["en", "mi"],
    primaryLanguage: "en",
    currency: "NZD",
    timezone: "Pacific/Auckland",
    paymentMethods: ["paypal", "bank_transfer"],
    dateFormat: "DD/MM/YYYY",
    numberFormat: "en-NZ"
  }
};

export const currencies = {
  "INR": { symbol: "₹", name: "Indian Rupee" },
  "USD": { symbol: "$", name: "US Dollar" },
  "EUR": { symbol: "€", name: "Euro" },
  "GBP": { symbol: "£", name: "British Pound" },
  "AED": { symbol: "د.إ", name: "UAE Dirham" },
  "SAR": { symbol: "﷼", name: "Saudi Riyal" },
  "SGD": { symbol: "S$", name: "Singapore Dollar" },
  "CAD": { symbol: "C$", name: "Canadian Dollar" },
  "AUD": { symbol: "A$", name: "Australian Dollar" },
  "PHP": { symbol: "₱", name: "Philippine Peso" },
  "IDR": { symbol: "Rp", name: "Indonesian Rupiah" },
  "MYR": { symbol: "RM", name: "Malaysian Ringgit" },
  "THB": { symbol: "฿", name: "Thai Baht" },
  "VND": { symbol: "₫", name: "Vietnamese Dong" },
  "KRW": { symbol: "₩", name: "South Korean Won" },
  "JPY": { symbol: "¥", name: "Japanese Yen" },
  "CNY": { symbol: "¥", name: "Chinese Yuan" },
  "BRL": { symbol: "R$", name: "Brazilian Real" },
  "MXN": { symbol: "Mex$", name: "Mexican Peso" },
  "ARS": { symbol: "$", name: "Argentine Peso" },
  "RUB": { symbol: "₽", name: "Russian Ruble" },
  "TRY": { symbol: "₺", name: "Turkish Lira" },
  "ZAR": { symbol: "R", name: "South African Rand" },
  "NGN": { symbol: "₦", name: "Nigerian Naira" },
  "KES": { symbol: "KSh", name: "Kenyan Shilling" },
  "EGP": { symbol: "E£", name: "Egyptian Pound" },
  "PKR": { symbol: "₨", name: "Pakistani Rupee" },
  "BDT": { symbol: "৳", name: "Bangladeshi Taka" },
  "LKR": { symbol: "Rs", name: "Sri Lankan Rupee" },
  "NPR": { symbol: "Rs", name: "Nepalese Rupee" },
  "PLN": { symbol: "zł", name: "Polish Złoty" },
  "SEK": { symbol: "kr", name: "Swedish Krona" },
  "NOK": { symbol: "kr", name: "Norwegian Krone" },
  "DKK": { symbol: "kr", name: "Danish Krone" },
  "CHF": { symbol: "CHF", name: "Swiss Franc" },
  "CZK": { symbol: "Kč", name: "Czech Koruna" },
  "HUF": { symbol: "Ft", name: "Hungarian Forint" },
  "RON": { symbol: "lei", name: "Romanian Leu" },
  "ILS": { symbol: "₪", name: "Israeli Shekel" },
  "NZD": { symbol: "NZ$", name: "New Zealand Dollar" }
};

export const languages = {
  "en": { name: "English", nativeName: "English" },
  "hi": { name: "Hindi", nativeName: "हिन्दी" },
  "bn": { name: "Bengali", nativeName: "বাংলা" },
  "te": { name: "Telugu", nativeName: "తెలుగు" },
  "mr": { name: "Marathi", nativeName: "मराठी" },
  "ta": { name: "Tamil", nativeName: "தமிழ்" },
  "gu": { name: "Gujarati", nativeName: "ગુજરાતી" },
  "kn": { name: "Kannada", nativeName: "ಕನ್ನಡ" },
  "ml": { name: "Malayalam", nativeName: "മലയാളം" },
  "pa": { name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  "es": { name: "Spanish", nativeName: "Español" },
  "fr": { name: "French", nativeName: "Français" },
  "de": { name: "German", nativeName: "Deutsch" },
  "pt": { name: "Portuguese", nativeName: "Português" },
  "ar": { name: "Arabic", nativeName: "العربية" },
  "fil": { name: "Filipino", nativeName: "Filipino" },
  "id": { name: "Indonesian", nativeName: "Bahasa Indonesia" },
  "ms": { name: "Malay", nativeName: "Bahasa Melayu" },
  "th": { name: "Thai", nativeName: "ไทย" },
  "vi": { name: "Vietnamese", nativeName: "Tiếng Việt" },
  "ko": { name: "Korean", nativeName: "한국어" },
  "ja": { name: "Japanese", nativeName: "日本語" },
  "zh-CN": { name: "Chinese (Simplified)", nativeName: "中文" },
  "ru": { name: "Russian", nativeName: "Русский" },
  "tr": { name: "Turkish", nativeName: "Türkçe" },
  "ur": { name: "Urdu", nativeName: "اردو" },
  "si": { name: "Sinhala", nativeName: "සිංහල" },
  "ne": { name: "Nepali", nativeName: "नेपाली" },
  "it": { name: "Italian", nativeName: "Italiano" },
  "pl": { name: "Polish", nativeName: "Polski" },
  "nl": { name: "Dutch", nativeName: "Nederlands" },
  "sv": { name: "Swedish", nativeName: "Svenska" },
  "no": { name: "Norwegian", nativeName: "Norsk" },
  "da": { name: "Danish", nativeName: "Dansk" },
  "fi": { name: "Finnish", nativeName: "Suomi" },
  "el": { name: "Greek", nativeName: "Ελληνικά" },
  "cs": { name: "Czech", nativeName: "Čeština" },
  "hu": { name: "Hungarian", nativeName: "Magyar" },
  "ro": { name: "Romanian", nativeName: "Română" },
  "he": { name: "Hebrew", nativeName: "עברית" },
  "af": { name: "Afrikaans", nativeName: "Afrikaans" },
  "zu": { name: "Zulu", nativeName: "isiZulu" },
  "xh": { name: "Xhosa", nativeName: "isiXhosa" },
  "yo": { name: "Yoruba", nativeName: "Yorùbá" },
  "ig": { name: "Igbo", nativeName: "Igbo" },
  "ha": { name: "Hausa", nativeName: "Hausa" },
  "sw": { name: "Swahili", nativeName: "Kiswahili" },
  "mi": { name: "Maori", nativeName: "Te Reo Māori" },
  "jv": { name: "Javanese", nativeName: "Basa Jawa" },
  "su": { name: "Sundanese", nativeName: "Basa Sunda" },
  "ca": { name: "Catalan", nativeName: "Català" },
  "eu": { name: "Basque", nativeName: "Euskara" },
  "gl": { name: "Galician", nativeName: "Galego" }
};
